//
//  MessagesInteractor.swift
//  GitHub-Messenger
//
//  Created by Luqman Fauzi on 4/3/2020.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MessagesInteractor {
}

// MARK: - Extensions -

extension MessagesInteractor: MessagesInteractorInterface {
}
