//
//  MessagesInterfaces.swift
//  GitHub-Messenger
//
//  Created by Luqman Fauzi on 4/3/2020.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MessagesWireframeInterface: WireframeInterface {
}

protocol MessagesViewInterface: ViewInterface {
    func setupViews()
    func scrollToBottom(animated: Bool)
    func performBatchUpdate(_ message: Message)
}

protocol MessagesPresenterInterface: PresenterInterface {
    func keyboardWillShow()
    func insertNewTextMessage(_ text: String)
    func appendNewMessage(_ message: Message)
    func showErrorMessage(_ message: String)
    
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> MessageContentItemInterface
}

protocol MessagesInteractorInterface: InteractorInterface {
}

/// Customise content item interface
protocol MessageContentItemInterface {
    var messageContent: MessageType { get }
    var direction: MessageDirection { get }
}
