//
//  UsersWireframe.swift
//  GitHub-Messenger
//
//  Created by Luqman Fauzi on 3/3/2020.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class UsersWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = UsersViewController()
        super.init(viewController: moduleViewController)

        let interactor = UsersInteractor()
        let presenter = UsersPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension UsersWireframe: UsersWireframeInterface {

    func openMessagingPage(_ user: User) {
        /// Present to Messages Module
        let messagesWireframe = MessagesWireframe(user: user)
        navigationController?.pushWireframe(messagesWireframe)
    }
}
