//
//  UsersInteractor.swift
//  GitHub-Messenger
//
//  Created by Luqman Fauzi on 3/3/2020.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class UsersInteractor {
    /// Interactor's constant values
    private struct Constants {
        static let dispatcherDelay: TimeInterval = 1.0
    }
}

// MARK: - Extensions -

extension UsersInteractor: UsersInteractorInterface {
    
    /// To make a request to GitHub's API
    /// - Parameter page: pagination
    /// - Parameter completion: API response either success response or error message
    func requestData(page: Pagination, completion: @escaping (_ result: Result<User.GitHubSuccessResponse, String>) -> Void) {
        GitHubService().getUsers(page: page) { (result) in
            DispatchQueue.main.asyncAfter(deadline: .now() + Constants.dispatcherDelay) {
                switch result {
                case .success(let response):
                    completion(.success(response))
                case .failure(let errorMessage):
                    completion(.failure(errorMessage))
                }
            }
        }
    }
}
