//
//  UsersInterfaces.swift
//  GitHub-Messenger
//
//  Created by Luqman Fauzi on 3/3/2020.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol UsersWireframeInterface: WireframeInterface {
    func openMessagingPage(_ user: User)
}

protocol UsersViewInterface: ViewInterface {
    func setupViews()
    func setLoadingView(_ show: Bool)
    func setListView(_ show: Bool)
    func setEmptyListView(_ show: Bool)
    func setLoadingPaginationView(_ show: Bool)
    func setLoadingPaginationViewWithRetry(_ show: Bool)
    func reloadData()
}

protocol UsersPresenterInterface: PresenterInterface {
    func refreshPage(_ sender: UIRefreshControl)
    func checkIfNeedsToLoadNextPage(offsetY: CGFloat, contentSizeHeight: CGFloat, frameHeight: CGFloat)
    func retryOnInitialLoad()
    func retryOnFailedToLoadNextPage()

    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> UserContentItemInterface
    func didSelectItem(at indexPath: IndexPath)
}

protocol UsersInteractorInterface: InteractorInterface {
    func requestData(page: Pagination, completion: @escaping (_ result: Result<User.GitHubSuccessResponse, String>) -> Void)
}

/// VIPER's model interface
protocol UserContentItemInterface {
    var title: String? { get }
    var imageURL: String? { get }
}
